### PR TITLE
Send heartbeat message back rabbitmq server.

### PR DESCRIPTION
**Pull request by tom-railpod**
See NoAck Consumers get socket closed by rabbitmq due to lack of heartbeat #98

In an environment where only unack'ed data was
consumed from a connection... rabbitmq-server
was closing the underlying socket.

This fix sends a heartbeat message back down the channel.

### CODE REVIEW

**Comment by gmr** [comment]
So my first reaction to this was that the heartbeat behavior is one where the server sends the heartbeat and the client replies. I reread the spec and it's pretty ambiguous as to the specific expected behavior.

I reviewed the code in rabbitmq-common and rabbitmq-server and it met my expectation that RabbitMQ thinks it should be sending heartbeats and expecting replies:

https://github.com/rabbitmq/rabbitmq-common/blob/aafe885f8782887e1cee4a531fa5c4369df49885/src/rabbit_reader.erl#L43

So I'm curious how your problem came to be in the first place. I've not seen any issues with a client being purely responsive to heartbeat frames with RabbitMQ, as long as it is responding.

**Comment by eandersson** [comment]
I ran into this with my library, and after talking to the RabbitMQ devs and they agreed with the behavior described in #99. 
https://groups.google.com/forum/#!searchin/rabbitmq-users/Erik%7Csort:relevance/rabbitmq-users/ZD8FgpcExn4/5n0PB85DAwAJ

**Comment by eandersson** [comment]
My new implementation for Heartbeats never replies to RabbitMQ heartbeats, but instead sends heartbeats only if there was no outgoing traffic.

**Comment by gmr** [comment]
@eandersson and it's held up ok with some long duration testing pretty well?

**Comment by gmr** [comment]
I appreciate the PR, but I don't think it's the right approach. One main thing is `rabbitpy.heartbeat.Checker` already has a built-in timer. Most, if not all of the logic desired could be applied inside `rabbitpy.heartbeat.Checker._check` without touching the unrelated `rabbitpy.channel0`. I'll rework heartbeat checking to more closely match the logic discussed by @eandersson  which should help in your situation.

**Comment by eandersson** [comment]
@gmr: Yep, not a single issue so far.

**Pull request closed without merging**
