### PR TITLE
Add User Specific Client Properties to AMQP Start OK

### PR DESCRIPTION
**Pull request by maarlo**

### CODE REVIEW

**Comment by jamesrusso** [comment]
I should have looked at this before I created #142, we both implemented it similarly.

**Comment by gmr** [comment]
My concern with this is it would allow someone with limited knowledge overwrite things like `capabilities`.

**Comment by maarlo** [comment]
What if the user could define only some safe capabilities?

**Comment by gmr** [comment]
I will add support for overwriting the non-capabilities client properties and specifying custom ones in the next version which is actively being worked on.

**Pull request closed without merging**
