### PR TITLE
Add configurable timeouts

### PR DESCRIPTION
**Pull request by vmarkovtsev**
As described in https://github.com/gmr/rabbitpy/issues/84

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
I see that it breaks 2.6. Unable to test it, unfortunately.

**Comment by gmr** [comment]
Thanks for that, would you mind resubmitting with only the timeout changes and split out the locale change to a new PR along with the bug  fix in the rabbitpy/amqp? It makes it easier to track that way.

Also your PR breaks in Python 2.6 and 3.2.

**Comment by vmarkovtsev** [comment]
done. Python 3.2 seems to be broken before my edits.

**Comment by vmarkovtsev** [comment]
If you take a look at the error, it is in [coverage](https://pypi.python.org/pypi/coverage) package, which clearly states that it does *not* support python 3.2. It used to support it, perhaps, but you forgot to freeze the versions in your requirements file.

**Comment by eandersson** [comment]
@gmr You need to add something like this for Coverage to work with Python 3.2, or don't use Coverage 4.x at all. =]
```
 - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install coverage==3.7.1; fi
```

**Pull request merged**
